<a href="https://colab.research.google.com/github/sheriff18/Me/blob/main/Sheriff_Alidu_Q3_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:

In [ ]:
NAME = "SHERIFF ALIDU"

---

# Q3

Let us start by importing `Numpy`.

In [ ]:

def import_numpy():
    """Import numpy as np."""
    import numpy as np
    return np




In [ ]:
"""Check that numpy is imported correctly"""

Create an array of 10 zeros

In [ ]:
def create_zeros():
    """Create an array of 10 zeros."""
    arr = np.zeros(10)
    return arr



In [ ]:
"""Check that create_zeros returns the correct output"""
print(create_zeros())


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create an array of 10 ones

In [ ]:
def create_ones():
    """Create an array of 10 ones."""
    arr = np.ones(10)
    return arr



In [ ]:
"""Check that create_ones returns the correct output"""
print(create_ones())


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Create an array of 10 fives

In [ ]:
def create_fives():
    """Create an array of 10 fives."""
    arr = np.full(10,5)
    return arr



In [ ]:
"""Check that create_fives returns the correct output"""
print(create_fives())



[5 5 5 5 5 5 5 5 5 5]


Create an array of the integers from 10 to 50

In [ ]:
def create_array_10_to_50():
    """Create an array of the integers from 10 to 50."""
    arr = np.arange(1,51)
    return arr



In [ ]:
"""Check that create_array_10_to_50 returns the correct output"""
print(create_array_10_to_50())


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
def create_matrix_0_to_8():
    """Create a 3x3 matrix with values ranging from 0 to 8."""
    arr_of_values = np.arange(0,9)
    matr = arr_of_values.reshape(3,3)
    return matr



In [ ]:
"""Check that create_matrix_0_to_8 returns the correct output"""
print(create_matrix_0_to_8())

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Use NumPy to generate a random number between 0 and 1

In [ ]:
def create_random_number():
    """Generate a random number between 0 and 1."""
    rand = np.random.rand()
    return rand



In [ ]:
"""Check that create_random_number returns the correct output"""
print(create_random_number())

0.32472610897223


Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
from numpy.core.arrayprint import array_repr
def create_random_numbers():
    """Generate an array of 25 random numbers from a standard normal distribution."""
    arr = np.random.randn(25)
    return arr



In [ ]:
"""Check that create_random_numbers returns the correct output"""
print(create_random_numbers())

[-0.00821227 -0.733507   -0.22731086  2.37309754  1.58199667 -0.47290922
 -0.57429907 -1.35541096 -1.24774949  0.53680657  0.87335265 -0.22260173
 -0.82059459  0.95433633  1.42599865  0.75121316 -0.57335376 -0.0052368
  1.04945093 -2.13607138 -0.72154454  0.22079433  2.84295476 -0.57851027
  0.49291503]


q) Write a function that accepts a numpy array and a threshold value, and returns a new array that contains only the elements of the input array that are greater than the threshold.


In [ ]:
def select_greater_than(array, threshold):
    """Return a new array that contains only the elements of the input array that are greater than the threshold."""
    new_arr =  array[array > threshold]
    return new_arr



In [ ]:
"""Check that select_greater_than returns the correct output for several inputs"""
array = np.array([1,2,4,6,7])
threshold = 4

print(select_greater_than(array,threshold))

[6 7]


q) Write a function that accepts a numpy array and a scalar value, and returns a new array that is the result of adding the scalar value to each element of the input array (using broadcasting).


In [ ]:
def add_scalar(array, scalar):





    """Return a new array that is the result of adding the scalar value to each element of the input array."""
    res = array + scalar
    return res



In [ ]:
"""Check that add_scalar returns the correct output for several inputs"""
array = np.array([1,2,4,6])
scalar = 1

print((add_scalar(array,scalar)))


[2 3 5 7]
